default: &default
  host: <%= ENV["DB_HOST"] %>
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: <%= ENV["rails_db"] %>
  username: <%= ENV["rails_user"] %>
  password: <%= ENV["rails_db"] %>


development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
